/**
 * Private member catalog — sections and line items as provided for the site.
 */
export const CATALOG_SECTIONS = [
  {
    title: "Compounds & materials",
    items: [
      "Lemon Bottle Fat Dissolver",
      "Retatrutide 60mg",
      "Retatrutide 40mg",
      "Retatrutide 20mg",
      "Retatrutide 10mg",
      "Retatrutide 5mg",
      "Tirzepatide 5mg",
      "Tirzepatide 10mg",
      "Tirzepatide 20mg",
      "Tirzepatide 30mg",
      "Semaglutide 5mg",
      "Semaglutide 10mg",
      "Semaglutide 15mg",
      "Semaglutide 20mg",
      "Semaglutide 25mg",
      "Semaglutide 30mg",
      "MK677 powder",
      "SLU-PP-332 capsule 250mcg",
      "Adipotide 10mg",
      "Psyllium Husk powder",
      "Pure Psyllium Husk powder",
      "Natural Psyllium Husk powder",
      "L-Carnitine powder",
      "Orlistat powder",
      "Pure Creatine Monohydrate powder",
      "Urolithiasis A powder",
      "Rutin powder",
      "Pure Fulvic Acid",
      "Pumpkin Seed Extract powder",
    ],
  },
  {
    title: "Health Supplement",
    items: [
      "ATX-304",
      "Lutein & Zeaxanthin gummies",
      "5-Amino-1MQ capsule",
      "NAD 1000mg",
      "NAD 500mg",
      "Apigenin Extract",
      "Chamomile Extract Apigenin",
      "Apigenin 98%",
      "Pure Apigenin",
      "Pure Icariin",
      "Silymarin Powder",
      "Genistein Powder",
      "Pea protein",
      "Rice protein",
      "Hemp protein",
      "Whey protein",
      "Cocoa powder",
      "Cocoa nibs",
      "Cocoa beans",
      "Cocoa beans with yacon syrup",
      "Chocolate fruits",
      "Wheatgrass",
      "Camut grass",
      "Barley grass",
      "Oat grass",
      "Alfalfa",
      "Beetroot juice powder",
      "Carrot juice powder",
      "Strawberry powder",
      "Raspberry powder",
      "Blueberry powder",
      "Currant powder",
      "Cranberry powder",
      "Lingonberry powder",
      "Cloudberry powder",
      "Sea buckthorn powder",
      "Crowberry powder",
      "Amla berry powder",
      "Schisandra",
      "Oat drink powder",
      "Rice drink powder",
      "Almond drink powder",
      "Coconut milk powder",
      "Green tea",
      "Pine needles",
      "Fir needles",
      "Hojicha",
      "Matcha",
      "Magnesium",
      "Zinc",
      "Selenium",
      "Methylsulphonylmethane",
      "Iron",
      "Iodine",
      "Silicon",
      "Zeolite",
      "Pure Fulvic Acid",
      "Pure Quercetin Powder",
      "Rutin Powder",
    ],
  },
  {
    title: "Cosmetic Ingredients",
    items: [
      "Carboxymethyl Chitosan powder",
      "Ginsenoside powder",
      "Bemotrizinol powder",
      "Ghk-Cu 50mg",
      "Ghk-Cu 5mg",
      "Premium Alpha Arbutin Powder",
      "99.5% Alpha Arbutin Powder",
      "Pure Alpha Arbutin Powder",
      "Pure Alpha Arbutin",
      "Pure Beta Arbutin",
      "Beta Arbutin Powder",
      "Natural Beta Arbutin Powder",
      "Resveratrol 98% Powder",
      "Sodium Hyaluronate 99%",
      "Natural Ferulic Acid",
      "Ergothioneine Powder",
    ],
  },
  {
    title: "Active Pharmaceutical Ingredients (API)",
    items: [
      "SLU-PP-332 powder",
      "Minoxidil powder",
      "Estradiol Enanthate powder",
      "Estradiol powder",
      "Beta-Estradiol powder",
      "NMNH capsule",
      "JBSNF-000088 powder",
      "Bam-15 powder",
      "Rapamycin Powder",
      "Aniracetam Supplement",
      "Tianeptine Sodium Powder",
      "Finibut powder",
      "Diindolylmethane powder",
      "Na-selank powder",
      "5-Amino-1-methylquinolin-1-ium Chloride capsule",
      "Epithalon 10mg",
      "Kisspeptin Peptide powder",
      "PT141 Powder",
    ],
  },
  {
    title: "Veterinary Drug",
    items: [
      "Ivermectin powder",
      "Fenbendazole powder",
      "Amoxicillin powder",
      "Albendazole powder",
      "Mebendazole powder",
      "Enrofloxacin powder",
      "Praziquantel powder",
      "Levamisole Hydrochloride powder",
    ],
  },
  {
    title: "Peptide & research compound catalog",
    items: [
      "Semaglutide 5mg",
      "Semaglutide 10mg",
      "Semaglutide 15mg",
      "Semaglutide 20mg",
      "Semaglutide 30mg",
      "Tirzepatide 5mg",
      "Tirzepatide 10mg",
      "Tirzepatide 15mg",
      "Tirzepatide 20mg",
      "Tirzepatide 30mg",
      "Tirzepatide 40mg",
      "Tirzepatide 45mg",
      "Tirzepatide 50mg",
      "Tirzepatide 60mg",
      "Tirzepatide 80mg",
      "Tirzepatide 100mg",
      "Retatrutide 5mg",
      "Retatrutide 10mg",
      "Retatrutide 15mg",
      "Retatrutide 20mg",
      "Retatrutide 30mg",
      "Retatrutide 40mg",
      "Retatrutide 50mg",
      "Retatrutide 60mg",
      "Cagrilintide 5mg",
      "Cagrilintide 10mg",
      "Tesamorelin 5mg",
      "Tesamorelin 10mg",
      "Cagrilintide+Semaglutide 5mg",
      "Cagrilintide+Semaglutide 10mg",
      "GHK-CU 50mg",
      "GHK-CU 100mg",
      "Epithalon 10mg",
      "Epithalon 50mg",
      "MOTS-c 10mg",
      "MOTS-c 40mg",
      "Sermorelin Acetate 5mg",
      "Sermorelin Acetate 10mg",
      "Melanotan 2 10mg",
      "AOD9604 5mg",
      "CJC-1295 DAC 5mg",
      "CJC-1295 NO DAC 5mg",
      "CJC-1295 NO DAC 10mg",
      "CJC-1295 NO DAC 5mg + Ipamorelin 5mg",
      "Ipamorelin 5mg",
      "Ipamorelin 10mg",
      "BPC 157 5mg",
      "BPC 157 10mg",
      "TB500 5mg",
      "TB500 10mg",
      "TB500 (TB4) 10mg",
      "BPC 5mg + TB 5mg",
      "BPC 10mg + TB 10mg",
      "GLOW (BPC 157 10mg + GHK-CU 50mg + TB500 10mg)",
      "KLOW (BPC 157 10mg + GHK-CU 50mg + TB500 10mg + KPV 10mg)",
      "GLOW50 (CU 35mg + TB10 + BPC5)",
      "NAD+ 500mg",
      "NAD+ 1000mg",
      "HGH 10iu",
      "HGH 15iu",
      "HGH 24iu",
      "HGH 36iu",
      "HCG 5000iu",
      "HCG 10000iu",
      "SLU-PP-332 5mg",
      "Thymosin Alpha-1 5mg",
      "Thymosin Alpha-1 10mg",
      "SS-31 10mg",
      "SS-31 50mg",
      "Glutathione 1500mg",
      "Snap-8 10mg",
      "KPV 5mg",
      "KPV 10mg",
      "Lemon Bottle 10mg",
      "Semax 5mg",
      "Semax 10mg",
      "Selank 5mg",
      "Selank 10mg",
      "IGF-1LR3 0.1mg",
      "IGF-1LR3 1mg",
      "VIP 5mg",
      "VIP 10mg",
      "PT-141 10mg",
      "dihexa 5mg",
      "dihexa capsul 5mg",
      "DSIP 5mg",
      "DSIP 15mg",
      "GHRP-6 Acetate 5mg",
      "GHRP-6 Acetate 10mg",
      "HMG 75iu",
      "IGF-DES 1mg",
      "Lipo-C (various)",
      "Lipo-B (various)",
      "Bacteriostatic Water 3mL",
      "Bacteriostatic Water 10mL",
      "Ara-290 10mg",
      "Cerebrolysin 60mg",
      "Thymalin 10mg",
      "LL37 5mg",
      "Survodutide 10mg",
      "Pinealon 5mg",
      "Pinealon 10mg",
      "Pinealon 20mg",
      "KissPeptin-10 5mg",
      "KissPeptin-10 10mg",
      "Oxytocin Acetate 2mg",
      "Oxytocin Acetate 10mg",
      "Adipotide 5mg",
      "Follistatin 1mg",
      "FOXO4 10mg",
      "5-amino-1mq 5mg",
      "5-amino-1mq 50mg",
      "5-amino-1mq 50mg capsul",
      "PNC-27 10mg",
      "Vitamin B12 2mg",
      "Vitamin B12 10mg",
      "L-Carnitine 500mg",
      "Mazdutide 10mg",
      "Gonadorelin Acetate 2mg",
      "ACE-031 1mg",
      "AICAR 50mg",
      "GHRP-2 Acetate 5mg",
      "GHRP-2 Acetate 10mg",
      "PEG MGF 2mg",
      "Dermorphin 5mg",
      "EPO 3000 IU",
    ],
  },
];
